# Generated by Django 4.2 on 2023-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecollection',
            name='movies',
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='movies',
            field=models.ManyToManyField(to='movie_app.movie'),
        ),
    ]
